import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex min-h-screen flex-col items-center justify-between p-24 bg-gradient-to-tl from-stone-500 to-emerald-400`}>{children}</body>
    </html>
  )
}
